package Gui;
import Entity.Jadwal;
import Helper.KoneksiDb;
import Model.JadwalModel;
import java.awt.event.*;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class DataJdwlAdmin extends javax.swing.JFrame {
    DefaultTableModel model;
    Statement stat;
    ResultSet rs;

    public DataJdwlAdmin() {
        initComponents();
        setTitle("Data Jadwal");
        setLocationRelativeTo(null);
        String [] header={"ID","Hari","Jam"};
        model = new DefaultTableModel(header,0);
        datajdwl.setModel(model);
        tampil();
    }
    private void tampil(){
        try{
            KoneksiDb knksi = new KoneksiDb();
            Connection conn = knksi.getconection();
            stat=conn.createStatement();
            rs=stat.executeQuery("select *from jadwal");
            while(rs.next()){
                String[] row ={Integer.toString(rs.getInt(1)),rs.getString(2),rs.getString(3)};
                model.addRow(row);
            }
            
        }catch(Exception e){
            System.out.println(e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        bg = new javax.swing.JPanel();
        tbljdwl = new javax.swing.JScrollPane();
        datajdwl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Ubah = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        TambahJwl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(255, 51, 51));
        back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, 96, -1));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1000, 700));

        datajdwl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        datajdwl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        datajdwl.setPreferredSize(new java.awt.Dimension(800, 400));
        tbljdwl.setViewportView(datajdwl);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("DATA JADWAL");

        Ubah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ubah.setText("Ubah");
        Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahActionPerformed(evt);
            }
        });

        Hapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        TambahJwl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TambahJwl.setText("Tambah");
        TambahJwl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahJwlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(TambahJwl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(317, 317, 317)
                                .addComponent(jLabel1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(tbljdwl, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbljdwl, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TambahJwl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        MenuAdmin dsn = new MenuAdmin();
        dsn.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahActionPerformed
        // TODO add your handling code here:
        JadwalModel mhs = new JadwalModel();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Masukkan ID Jadwal"));
        
        String test = JOptionPane.showInputDialog("Masukkan Hari yang Baru");
        if(test.length()>0){
            mhs.updateHari(test,id);
            DataJdwlAdmin dtmhs = new DataJdwlAdmin();
            dispose();
            dtmhs.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "Data Kosong");
        }
    }//GEN-LAST:event_UbahActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        JadwalModel mhs = new JadwalModel();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Masukkan ID Jadwal"));
        
        if(id>-1){
            mhs.deleteJadwal(id);
            DataJdwlAdmin dtmhs = new DataJdwlAdmin();
            dispose();
            dtmhs.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "Data Kosong");
        }
    }//GEN-LAST:event_HapusActionPerformed

    private void TambahJwlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahJwlActionPerformed
        Jadwal ent = new Jadwal();
        JadwalModel mdl = new JadwalModel();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Masukkan ID Jadwal yang Baru"));
        String hari = JOptionPane.showInputDialog("Masukkan Hari yang Baru");
        String jam = JOptionPane.showInputDialog("Masukkan Jam yang Baru");
        if(hari.length()>0){
            mdl.insertData(new Jadwal(id,hari,jam));
            DataJdwlAdmin dtmhs = new DataJdwlAdmin();
            dispose();
            dtmhs.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "Data Kosong");
        }
    }//GEN-LAST:event_TambahJwlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataJdwlAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataJdwlAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataJdwlAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataJdwlAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataJdwlAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JButton TambahJwl;
    private javax.swing.JButton Ubah;
    private javax.swing.JButton back;
    private javax.swing.JPanel bg;
    private javax.swing.JTable datajdwl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane tbljdwl;
    // End of variables declaration//GEN-END:variables
}
