package Gui;
import Entity.Matkul;
import Helper.KoneksiDb;
import Model.MatkulModel;
import java.awt.event.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class DataMkAdmin extends javax.swing.JFrame {
    DefaultTableModel model;
    Statement stat;
    ResultSet rs;

    public DataMkAdmin() {
        initComponents();
        setTitle("Data Mahasiswa");
        setLocationRelativeTo(null);
        String [] header={"ID","Kode","Nama","SKS","Semester"};
        model = new DefaultTableModel(header,0);
        datamk.setModel(model);
        tampil();
    }
    private void tampil(){
        try{
            KoneksiDb knksi = new KoneksiDb();
            Connection conn = knksi.getconection();
            stat=conn.createStatement();
            rs=stat.executeQuery("select *from matkul");
            while(rs.next()){
                String[] row ={Integer.toString(rs.getInt(1)),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                model.addRow(row);
            }
            
        }catch(Exception e){
            System.out.println(e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        bg = new javax.swing.JPanel();
        tblmk = new javax.swing.JScrollPane();
        datamk = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Ubah = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        TambahMk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(255, 51, 51));
        back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, 96, -1));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1000, 700));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datamk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        datamk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        datamk.setPreferredSize(new java.awt.Dimension(800, 400));
        datamk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datamkMouseClicked(evt);
            }
        });
        tblmk.setViewportView(datamk);

        bg.add(tblmk, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 98, 879, 353));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("DATA MATA KULIAH");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 48, -1, -1));

        Ubah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ubah.setText("Ubah");
        Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahActionPerformed(evt);
            }
        });
        bg.add(Ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 115, 41));

        Hapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        bg.add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 115, 41));

        TambahMk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TambahMk.setText("Tambah");
        TambahMk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahMkActionPerformed(evt);
            }
        });
        bg.add(TambahMk, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 110, 40));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        MenuAdmin dsn = new MenuAdmin();
        dsn.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void datamkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datamkMouseClicked
        
    }//GEN-LAST:event_datamkMouseClicked

    private void UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahActionPerformed
        // TODO add your handling code here:
        MatkulModel mhs = new MatkulModel();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Masukkan ID Matkul"));
        
        String test = JOptionPane.showInputDialog("Masukkan Nama Mata Kuliah yang Baru");
        if(test.length()>0){
            mhs.updateNamaMK(test,id);
            DataMkAdmin dtmhs = new DataMkAdmin();
            dispose();
            dtmhs.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "Data Kosong");
        }
    }//GEN-LAST:event_UbahActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        MatkulModel mhs = new MatkulModel();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Masukkan ID Mata Kuliah"));
        
        if(id>-1){
            mhs.deleteMatkul(id);
            DataMkAdmin dtmhs = new DataMkAdmin();
            dispose();
            dtmhs.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "Data Kosong");
        }
    }//GEN-LAST:event_HapusActionPerformed

    private void TambahMkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahMkActionPerformed
        MatkulModel mdl = new MatkulModel();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Masukkan ID Matkul yang Baru"));
        String kode = JOptionPane.showInputDialog("Masukkan Kode Matkul yang Baru");
        String nama = JOptionPane.showInputDialog("Masukkan Nama Matkul yang Baru");
        int sks = Integer.parseInt(JOptionPane.showInputDialog("Masukkan SKS yang Baru"));
        int sem = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Semester yang Baru"));
        if(kode.length()>0){
            mdl.insertData(new Matkul(id,kode,nama,sks,sem));
            DataMkAdmin dtmhs = new DataMkAdmin();
            dispose();
            dtmhs.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "Data Kosong");
        }
    }//GEN-LAST:event_TambahMkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataMkAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataMkAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataMkAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataMkAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataMkAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JButton TambahMk;
    private javax.swing.JButton Ubah;
    private javax.swing.JButton back;
    private javax.swing.JPanel bg;
    private javax.swing.JTable datamk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane tblmk;
    // End of variables declaration//GEN-END:variables
}
