package Gui;
import Entity.Mahasiswa;
import Helper.KoneksiDb;
import Model.MahasiswaModel;
import java.awt.event.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class DataMhsAdmin extends javax.swing.JFrame {
    DefaultTableModel model;
    Statement stat;
    ResultSet rs;

    public DataMhsAdmin() {
        initComponents();
        setTitle("Data Mahasiswa");
        setLocationRelativeTo(null);
        String [] header={"ID","Nama","NPM","Alamat","No Telp","Password"};
        model = new DefaultTableModel(header,0);
        datamhs.setModel(model);
        tampil();
    }
    private void tampil(){
        try{
            KoneksiDb knksi = new KoneksiDb();
            Connection conn = knksi.getconection();
            stat=conn.createStatement();
            rs=stat.executeQuery("select *from mahasiswa");
            while(rs.next()){
                String[] row ={Integer.toString(rs.getInt(1)),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)};
                model.addRow(row);
            }
            
        }catch(Exception e){
            System.out.println(e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        bg = new javax.swing.JPanel();
        tblmhs = new javax.swing.JScrollPane();
        datamhs = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Ubah = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        TambahMhs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(255, 51, 51));
        back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, 96, -1));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1000, 700));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datamhs.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        datamhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        datamhs.setPreferredSize(new java.awt.Dimension(800, 400));
        datamhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datamhsMouseClicked(evt);
            }
        });
        tblmhs.setViewportView(datamhs);

        bg.add(tblmhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 98, 879, 353));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("DATA MAHASISWA");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        Ubah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ubah.setText("Ubah");
        Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahActionPerformed(evt);
            }
        });
        bg.add(Ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 115, 41));

        Hapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        bg.add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 115, 41));

        TambahMhs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TambahMhs.setText("Tambah");
        TambahMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahMhsActionPerformed(evt);
            }
        });
        bg.add(TambahMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 500, 113, 41));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        MenuAdmin dsn = new MenuAdmin();
        dsn.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void datamhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datamhsMouseClicked
        
    }//GEN-LAST:event_datamhsMouseClicked

    private void UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahActionPerformed
        // TODO add your handling code here:
        MahasiswaModel mhs = new MahasiswaModel();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Masukkan ID Mahasiswa"));
        
        String test = JOptionPane.showInputDialog("Masukkan Nama Mahasiswa yang Baru");
        if(test.length()>0){
            mhs.updateNama(test,id);
            DataMhsAdmin dtmhs = new DataMhsAdmin();
            dispose();
            dtmhs.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "Data Kosong");
        }
    }//GEN-LAST:event_UbahActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        MahasiswaModel mhs = new MahasiswaModel();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Masukkan ID Mahasiswa"));
        
        if(id>-1){
            mhs.deleteMahasiswa(id);
            DataMhsAdmin dtmhs = new DataMhsAdmin();
            dispose();
            dtmhs.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "Data Kosong");
        }
    }//GEN-LAST:event_HapusActionPerformed

    private void TambahMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahMhsActionPerformed
        MahasiswaModel mdl = new MahasiswaModel();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Masukkan ID Mahasiswa yang Baru"));
        String nama = JOptionPane.showInputDialog("Masukkan Nama Mahasiswa yang Baru");
        String nip = JOptionPane.showInputDialog("Masukkan NPM yang Baru");
        String alamat = JOptionPane.showInputDialog("Masukkan Alamat yang Baru");
        String notelp = JOptionPane.showInputDialog("Masukkan No Telp yang Baru");
        String pw = JOptionPane.showInputDialog("Masukkan Password yang Baru");
        if(nama.length()>0){
            mdl.insertData(new Mahasiswa(id,nama,nip,alamat,notelp,pw));
            DataMhsAdmin dtmhs = new DataMhsAdmin();
            dispose();
            dtmhs.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Data Kosong");
        }
    }//GEN-LAST:event_TambahMhsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataMhsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataMhsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataMhsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataMhsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataMhsAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JButton TambahMhs;
    private javax.swing.JButton Ubah;
    private javax.swing.JButton back;
    private javax.swing.JPanel bg;
    private javax.swing.JTable datamhs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane tblmhs;
    // End of variables declaration//GEN-END:variables
}
