package Gui;
import Entity.DetailKrs;
import Entity.Jadwal;
import Entity.Mahasiswa;
import Helper.KoneksiDb;
import Model.DetailKrsModel;
import Model.JadwalModel;
import java.awt.event.*;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class DataDaftarKRS extends javax.swing.JFrame {
    DefaultTableModel model;
    Statement stat;
    ResultSet rs;
    Connection conn = Helper.KoneksiDb.getconection();
    private int sem;
    private String npm1;
    public DataDaftarKRS() {
        initComponents();
        setTitle("Daftar KRS");
        setLocationRelativeTo(null);
        String [] header={"ID Kartu Studi","Nama Mata Kuliah","Nama Dosen","Hari","Jam","Nama Ruang"};
        model = new DefaultTableModel(header,0);
        datajdwl.setModel(model);
        sem = Integer.parseInt(JOptionPane.showInputDialog(null,"Masukkan Semester Anda"));
        npm1 = JOptionPane.showInputDialog(null,"Masukkan NPM Anda");
        tampil();
        try {
            String sql = "SELECT id_mhs FROM mahasiswa WHERE npm='"+npm1+"'";
            stat = conn.createStatement();
            rs = stat.executeQuery(sql);
            while(rs.next()){
                idmhs.setText(Integer.toString(rs.getInt("id_mhs")));
            }
        }catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    private void tampil(){
        try{
            KoneksiDb knksi = new KoneksiDb();
            Connection conn = knksi.getconection();
            stat=conn.createStatement();
            rs=stat.executeQuery("select kartu_studi.id_ks,nama_matkul,nama_dosen,hari,jam,nama_ruang from mahasiswa "
                    + "join detail_krs on mahasiswa.id_mhs=detail_krs.id_mhs "
                    + "join kartu_studi on kartu_studi.id_ks=detail_krs.id_ks "
                    + "join matkul on matkul.id_matkul=kartu_studi.id_matkul "
                    + "join dosen on dosen.id_dosen=kartu_studi.id_dosen "
                    + "join ruang on ruang.id_ruang=kartu_studi.id_ruang "
                    + "join jadwal on jadwal.id_jadwal=kartu_studi.id_jadwal "
                    +"where semester"+sem
            );
            while(rs.next()){
                String[] row ={Integer.toString((rs.getInt(1))),rs.getString(2),rs.getString(3),
                    rs.getString(4),rs.getString(5),rs.getString(6)};
                model.addRow(row);                
            }  
        }catch(Exception e){
            System.out.println(e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        bg = new javax.swing.JPanel();
        tbljdwl = new javax.swing.JScrollPane();
        datajdwl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        AmbilKrs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idmhs = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(255, 51, 51));
        back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, 96, -1));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1000, 700));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datajdwl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        datajdwl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        datajdwl.setPreferredSize(new java.awt.Dimension(800, 400));
        tbljdwl.setViewportView(datajdwl);

        bg.add(tbljdwl, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 106, 879, 353));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("DAFTAR KRS");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 44, -1, -1));

        AmbilKrs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AmbilKrs.setText("Ambil KRS");
        AmbilKrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmbilKrsActionPerformed(evt);
            }
        });
        bg.add(AmbilKrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 477, 133, 48));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID Mahasiswa :");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 125, 20));

        idmhs.setEditable(false);
        idmhs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idmhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idmhsActionPerformed(evt);
            }
        });
        bg.add(idmhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 40, 30));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        MenuMhs dsn = new MenuMhs();
        dsn.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void AmbilKrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmbilKrsActionPerformed

        DetailKrsModel mdl = new DetailKrsModel();
        int tes = Integer.parseInt(JOptionPane.showInputDialog("Masukkan ID Mahasiswa anda"));
        int id = Integer.parseInt(JOptionPane.showInputDialog("Masukkan ID Kartu Studi yang akan dipilih"));
        if(tes>0){
            mdl.insertData(new DetailKrs(tes,id));
            MenuMhs dtmhs = new MenuMhs();
            dispose();
            dtmhs.setVisible(true);

        }else{
            JOptionPane.showMessageDialog(null, "Data Kosong");
        }
    }//GEN-LAST:event_AmbilKrsActionPerformed

    private void idmhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idmhsActionPerformed

    }//GEN-LAST:event_idmhsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataDaftarKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataDaftarKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataDaftarKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataDaftarKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataDaftarKRS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AmbilKrs;
    private javax.swing.JButton back;
    private javax.swing.JPanel bg;
    private javax.swing.JTable datajdwl;
    private javax.swing.JTextField idmhs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane tbljdwl;
    // End of variables declaration//GEN-END:variables
}
