package Gui;

import java.awt.event.ActionEvent;
import java.sql.*;
import javax.swing.JOptionPane;
public class LoginMhs extends javax.swing.JFrame {

    private String sql;
    ResultSet rs;
    Statement stat;
    Connection conn = Helper.KoneksiDb.getconection();
    public LoginMhs() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Login Mahasiswa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fieldnpm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fieldpw = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 120, 40));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        jLabel3.setText("MAHASISWA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 280, -1));

        fieldnpm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fieldnpm.setName("fieldnpm"); // NOI18N
        fieldnpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldnpmActionPerformed(evt);
            }
        });
        jPanel1.add(fieldnpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 155, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("NPM           : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 152, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Password    :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 141, 46));

        fieldpw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(fieldpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 155, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginmhs.jpg"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 350, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldnpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldnpmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldnpmActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        try {
            sql = "SELECT * FROM mahasiswa WHERE npm='"+fieldnpm.getText()+"' AND password_mhs='"+fieldpw.getText()+"'";
            stat = conn.createStatement();
            rs = stat.executeQuery(sql);
            if(rs.next()){
                if(fieldnpm.getText().equals(rs.getString("npm")) && fieldpw.getText().equals(rs.getString("password_mhs"))){
                    JOptionPane.showMessageDialog(null, "Berhasil login","Login Mahasiswa",JOptionPane.INFORMATION_MESSAGE);
                    JOptionPane.showMessageDialog(null, "Selamat datang, "+rs.getString("nama_mhs"),"Login Mahasiswa",JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    MenuMhs dsn=new MenuMhs();
                    dsn.setVisible(true);
                }
                }else{
                    JOptionPane.showMessageDialog(null, "Gagal Login","Login Mahasiswa",JOptionPane.INFORMATION_MESSAGE);
                    fieldnpm.setText(null);
                    fieldpw.setText(null);
                }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }   

    }//GEN-LAST:event_LoginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        Login lgn = new Login();
        lgn.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new LoginMhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JTextField fieldnpm;
    private javax.swing.JPasswordField fieldpw;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
