/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

/**
 *
 * @author Lenovo
 */
public class MenuAdmin extends javax.swing.JFrame {

    public MenuAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Menu Dosen");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        ViewMhs = new javax.swing.JButton();
        ViewJdwl = new javax.swing.JButton();
        ViewMtkl = new javax.swing.JButton();
        ViewRg = new javax.swing.JButton();
        ViewDsn = new javax.swing.JButton();
        ViewKS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU ADMIN");

        back.setBackground(new java.awt.Color(255, 51, 51));
        back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        ViewMhs.setBackground(new java.awt.Color(51, 153, 255));
        ViewMhs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ViewMhs.setForeground(new java.awt.Color(255, 255, 255));
        ViewMhs.setText("Tampilkan Daftar Mahasiswa");
        ViewMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMhsActionPerformed(evt);
            }
        });

        ViewJdwl.setBackground(new java.awt.Color(51, 153, 255));
        ViewJdwl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ViewJdwl.setForeground(new java.awt.Color(255, 255, 255));
        ViewJdwl.setText("Tampilkan Daftar Jadwal");
        ViewJdwl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewJdwlActionPerformed(evt);
            }
        });

        ViewMtkl.setBackground(new java.awt.Color(51, 153, 255));
        ViewMtkl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ViewMtkl.setForeground(new java.awt.Color(255, 255, 255));
        ViewMtkl.setText("Tampilkan Daftar Matkul");
        ViewMtkl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMtklActionPerformed(evt);
            }
        });

        ViewRg.setBackground(new java.awt.Color(51, 153, 255));
        ViewRg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ViewRg.setForeground(new java.awt.Color(255, 255, 255));
        ViewRg.setText("Tampilkan Daftar Ruang");
        ViewRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRgActionPerformed(evt);
            }
        });

        ViewDsn.setBackground(new java.awt.Color(51, 153, 255));
        ViewDsn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ViewDsn.setForeground(new java.awt.Color(255, 255, 255));
        ViewDsn.setText("Tampilkan Daftar Dosen");
        ViewDsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDsnActionPerformed(evt);
            }
        });

        ViewKS.setBackground(new java.awt.Color(51, 153, 255));
        ViewKS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ViewKS.setForeground(new java.awt.Color(255, 255, 255));
        ViewKS.setText("Tampilkan Daftar Kartu Studi");
        ViewKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewKSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(ViewJdwl, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(ViewMtkl, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewDsn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewKS, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewRg, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)))
                .addGap(18, 18, 18)
                .addComponent(ViewDsn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewMtkl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewJdwl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewRg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ViewKS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        LoginDsn lgn = new LoginDsn();
        lgn.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void ViewMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMhsActionPerformed
        // TODO add your handling code here:
        dispose();
        DataMhsAdmin lgn = new DataMhsAdmin();
        lgn.setVisible(true);
    }//GEN-LAST:event_ViewMhsActionPerformed

    private void ViewJdwlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewJdwlActionPerformed
        // TODO add your handling code here:
        dispose();
        DataJdwlAdmin lgn = new DataJdwlAdmin();
        lgn.setVisible(true);
    }//GEN-LAST:event_ViewJdwlActionPerformed

    private void ViewMtklActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMtklActionPerformed
        // TODO add your handling code here:
        dispose();
        DataMkAdmin lgn = new DataMkAdmin();
        lgn.setVisible(true);
    }//GEN-LAST:event_ViewMtklActionPerformed

    private void ViewRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRgActionPerformed
        // TODO add your handling code here:
        dispose();
        DataRgAdmin lgn = new DataRgAdmin();
        lgn.setVisible(true);
    }//GEN-LAST:event_ViewRgActionPerformed

    private void ViewDsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDsnActionPerformed
        dispose();
        DataDsnAdmin lgn = new DataDsnAdmin();
        lgn.setVisible(true);
    }//GEN-LAST:event_ViewDsnActionPerformed

    private void ViewKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewKSActionPerformed
        dispose();
        DataKSAdmin lgn = new DataKSAdmin();
        lgn.setVisible(true);
    }//GEN-LAST:event_ViewKSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewDsn;
    private javax.swing.JButton ViewJdwl;
    private javax.swing.JButton ViewKS;
    private javax.swing.JButton ViewMhs;
    private javax.swing.JButton ViewMtkl;
    private javax.swing.JButton ViewRg;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
